version: '3'

services:

  spring-boot-s8-app:
    container_name: s8bc-app
    build:
      context: .
      dockerfile: Dockerfile
    image: spring-boot-s8-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{"spring":{"datasource":{"url":"jdbc:mysql://mysqldb:3306/challenge","username":"root","password":"root"},"jpa":{"hibernate":{"ddl-auto":"create-drop"},"database-platform":"org.hibernate.dialect.MySQLDialect"}}}'
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    depends_on:
      - mysqldb

  mysqldb:
    container_name: mysqldb
    image: mysql:8-oracle
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: challenge
      MYSQL_ROOT_PASSWORD: root