version: '3'

services:

  mysqldb:
    container_name: mysqldb
    image: mysql:8-oracle
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: challenge
      MYSQL_ROOT_PASSWORD: root